version: '3'

services:
  nodejs:
    build:
      context: deployment
      dockerfile: Dockerfile
    image: express_ts-app:alpine_ms
    container_name: challange-getir
    environment:
      - PORT=7817
      - MONGODB_URI=mongodb+srv://challengeUser:WUMglwNBaydH8Yvu@challenge-xzwqd.mongodb.net/getir-case-study?authSource=admin&replicaSet=challenge-shard-0&readPreference=primary&appname=MongoDB%20Compass&retryWrites=true&ssl=true
      - CURRENT_API_VERSION=V1
      - LOGGER_FORMAT="combined"
    ports:
      - "7817:7817"

